### PR TITLE
Window fix

### PR DESCRIPTION
**Pull request by ItsEasyActually**
Due to some unfortunate tomfoolery and other general we made some mistakes and here's hoping we can rectify them. 

Proposal: 
Window Config for the internal maintainAspectRatio option will be enabled by default, and will be disabled if the corresponding settings `settings.KeepAspectOnResize` is set to true. This will effectively allow a "stretch to window" behavior. This should be close to 1:1 with the original behavior before the merge into the SAMM with only the bool handling being inversed now. 

Video showcasing changes in action (Please be aware that the Keep Aspect On Resize has not been renamed in this video, see the Notes section for more info):

https://github.com/X-Hax/sa2-mod-loader/assets/8052134/4d483193-3f46-433b-b390-a63d064edda2

Notes:
 - Settings:
   - **Windowed:** When the corresponding bool is set to true, the window will automatically update the internal resolution when scaled.
   - **Borderless Fullscreen:** When the corresponding bool is set to true, the inner window (game window) will be stretched to the outer window's size.
   - **Custom Window:** Same behavior as Borderless Fullscreen, but it's a standard window and fullscreened.
 - The display name for the `Keep Aspect On Resize` option will change in the manager, but it will still be written to the settings file as `KeepAspectOnResize`. Altering this in the manager _is_ an option, but it may have some unintended side effects and isn't advisable. It should be fine to alter the name in the loader's settings however, but it will cause a minor inconsistency between the settings file and what setting it applies to within the loader.

### CODE REVIEW

**Comment by ItsEasyActually** [comment]
Following this up with discussion kellsnc and I had after making this PR. We agreed it should be okay to make the changes to the settings configuration on the manager's side and then update the loader to follow those settings as necessary. 

My reason for this decision boils down to two points: 
1. The `Keep Aspect Ratio on Resize` setting, as it was originally made, being completely useless going forward. It's easier to just change it internally in the config on the Manager's side. It will be made into a `Stretch to Window` Config option.
2. It's much better for us to make changes where we keep option names consistent instead of using names that don't make sense for their intended setting, even internally, going forward. 

Will update this PR once the Manager side has been updated with the necessary changes, and we can proceed with the updates.

**Comment by ItsEasyActually** [comment]
Manager side as been updated with the new settings, PR open [here](https://github.com/X-Hax/SA-Mod-Manager/pull/140). That PR will remain open and pending until the changes on this side have been finalized and ready to released.

**Comment by kellsnc** [comment]
Following changes have been made:
- Allow resizing in CustomWindowMode (the inner window will center, this behavior can be changed if needed)
- Added an option to remove the border image to show black bars instead. Some people might prefer less distractions on the side. It also improves resizing performance.
- Replace MaintainAspectRatio setting with StretchToWindow
- Alt+Tab will work properly with multiple monitors. Note: for now, if the monitor hosting the fullscreen window is disconnected, it will break returning to windowed.
- Fix a small calculation issue with MaintainAspectRatio.
- Bumped the ModLoaderVer to 14 for the new settings.

**Comment by ItsEasyActually** [comment]
Went testing as we're gearing up to do releases across the board for both loaders and the manager and have found that there's a bug. If you enable the window resize option on the Custom Window, the inner window does not keep its rendering size. 

no-resize
yes-resize

In the above images, the settings Custom Window, Render Res at 640x480 and Window Size at 1280x720. The first image does not have Resizable Window toggled, but the second image does. The inner window's resolution in the second image is bumped to 720 (and scales when resizing the window) when the intended behavior should be keeping the inner window locked to 640x480.

**Comment by ItsEasyActually** [comment]
And we are good to go as of [fa818ec](https://github.com/X-Hax/sa2-mod-loader/commit/fa818ec09408d8bb747e80a4f6414a0c57639730)

**Pull request merged**
